apiVersion: v1
kind: Service
metadata:
  name: hadoop-service
spec:
  selector:
    app: hadoop
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088
  - protocol: TCP
    port: 9870
    targetPort: 9870
  - protocol: TCP
    port: 9864
    targetPort: 9864
  - protocol: TCP
    port: 9866
    targetPort: 9866
  type: NodePort
